[project]
name = "dz-21-2"
version = "0.1.0"
description = ""
authors = [
    {name = "Юлия Бусыгина",email = "ubusygina747@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "dz_21"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
